### ISSUE TITLE
libnekit 可以实现ssr么？

### ISSUE THREAD

**Issue by zhuwudan** [zhuhaow/libnekit#10]
你好，libnekit 可以实现ssr么？

**Comment by zhuhaow** [comment]
可以自己实现

**Comment by zhuwudan** [comment]
有这个库demo么？能否传我一份，谢谢！

**Comment by zhuhaow** [comment]
ssr本身不是开源的么

**Comment by zhuwudan** [comment]
我看您这个库挺有意思的，但是我还没研究出来怎么使用，能否传我一份demo，让我学习一下？

**Comment by zhuhaow** [comment]
把readme里面那个demo抄一下就可以跑了，至于data_flow怎么写，已经有很多例子了。

**Comment by zhuwudan** [comment]
我现在还没有成功弄到我的xcode项目中，并且执行这个也报错
pip install pipenv
Collecting pipenv
  Could not fetch URL https://pypi.python.org/simple/pipenv/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661) - skipping
  Could not find a version that satisfies the requirement pipenv (from versions: )
No matching distribution found for pipenv

**Comment by zhuhaow** [comment]
升级 pip 
curl https://bootstrap.pypa.io/get-pip.py | python3

我也没试过用xcode

**Comment by zhuwudan** [comment]
这个为何也报错呢？那这个库如何做iOS app？
curl https://bootstrap.pypa.io/get-pip.py | python3
-bash: python3: command not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  1 1604k    1 18648    0     0  11501      0  0:02:22  0:00:01  0:02:21 11504
curl: (23) Failed writing body (0 != 2759)

**Comment by zhuhaow** [comment]
报错是因为没有python3啊

如果做iOS app取决于你想要怎么做，这库就是一个C++库而已，没有任何特殊的地方。唯一特殊的地方可能是自带编译依赖的脚本。

**Comment by zhuwudan** [comment]
我之前学习过你的nekit，然后实现了VPN的功能，这个也是类似的么？

**Comment by zhuhaow** [comment]
这个是更快更强大的C++重写版

**Comment by zhuwudan** [comment]
我看描述中是这样说的，但是我不会使用，我想用这个做一个支持ssr的vpn应用

**Comment by zhuhaow** [comment]
不会用说明有一些基础知识要学习啊，我也没啥办法。

**Comment by zhuwudan** [comment]
。。。   方便加个好友么，想像你学习学习

**Comment by zhuwudan** [comment]
我的qq：1196918203

**Comment by zhuhaow** [comment]
向我没什么好学习的，多读书

**Comment by zhuwudan** [comment]
😄 好吧，谢谢
