### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by abit-me** [zhuhaow/libnekit#12]
// When a new connection comes in locally, we treat it as a connection to a
    // SOCSK5 server.
    auto socks5_listener = std::make_unique<transport::TcpListener>(
                                                                    instance.io(), [](auto data_flow) {
                                                                        return std::make_unique<data_flow::Socks5ServerDataFlow>(
                                                                                                                                 std::move(data_flow), data_flow->Session());
                                                                    });

When I compile the sample code on iOS, I encounter an error: No member named 'io' in netkit::Instance

**Comment by zhuhaow** [comment]
io is refactored as runloop. As libnekit is under heavy refactoring, expect doc to be outdated.

On 2 Sep 2018, at 20:01, abit-me <notifications@github.com> wrote:

// When a new connection comes in locally, we treat it as a connection to a
// SOCSK5 server.
auto socks5_listener = std::make_unique<transport::TcpListener>(
                                                                instance.io(), [](auto data_flow) {
                                                                    return std::make_unique<data_flow::Socks5ServerDataFlow>(
                                                                                                                             std::move(data_flow), data_flow->Session());
                                                                });
When I compile the sample code on iOS, I encounter an error: No member named 'io' in netkit::Instance

**Comment by zhuhaow** [comment]
Please check Travis config for how to build it as of now.

I'm closing this since I'll update the doc when things are more stable.
