### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by honbolau** [zhuhaow/libnekit#14]
➜  build git:(master) ✗ sudo cmake .. -DCMAKE_TOOLCHAIN_FILE=/Users/liuhongbao/Desktop/libnekit/cmake/toolchain/ios.cmake -DPLATFORM=ios

-- Building with Xcode version: 10.0
-- Configuring iOS build for platform: OS, architecture(s): arm64
-- Using SDK: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.0.sdk for platform: OS
-- Using the default min-version since IOS_DEPLOYMENT_TARGET not provided!
-- Enabling bitcode support by default. ENABLE_BITCODE not provided!
-- Using C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Using CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Using libtool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool
-- Building for minimum iOS version: 9.0 (SDK version: 12.0)
-- Version flags set to: -miphoneos-version-min=9.0
-- Enabling bitcode support.
-- Building with Xcode version: 10.0
-- Configuring iOS build for platform: OS, architecture(s): arm64
-- Using libtool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool
-- Building for minimum iOS version: 9.0 (SDK version: 12.0)
-- Version flags set to: -miphoneos-version-min=9.0
-- Enabling bitcode support.
-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Performing Test HAS_WALL
-- Performing Test HAS_WALL - Success
-- Performing Test HAS_WEXTRA
-- Performing Test HAS_WEXTRA - Success
-- Performing Test HAS_STRICT_ALIASING
-- Performing Test HAS_STRICT_ALIASING - Success
-- Performing Test HAS_PEDANTIC
-- Performing Test HAS_PEDANTIC - Success
-- Performing Test HAS_PRAGMA_ONCE_WARNING
-- Performing Test HAS_PRAGMA_ONCE_WARNING - Success
CMake Error at CMakeLists.txt:110 (include):
  include could not find load file:

    /Users/liuhongbao/Desktop/libnekit/build/conanbuildinfo.cmake

CMake Error at CMakeLists.txt:111 (conan_basic_setup):
  Unknown CMake command "conan_basic_setup".

-- Configuring incomplete, errors occurred!
See also "/Users/liuhongbao/Desktop/libnekit/build/CMakeFiles/CMakeOutput.log".
See also "/Users/liuhongbao/Desktop/libnekit/build/CMakeFiles/CMakeError.log".
➜  build git:(master) ✗ cmake --version
cmake version 3.12.3

**Comment by honbolau** [comment]
➜  libnekit git:(master) ✗ conan install . --build=missing -s compiler.libcxx=libstdc++
Configuration:
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=10.0
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]

libmaxminddb/1.3.2@zhuhaow/stable: Not found in local cache, looking in remotes...
libmaxminddb/1.3.2@zhuhaow/stable: Trying with 'conan-center'...
ERROR: Failed requirement 'libmaxminddb/1.3.2@zhuhaow/stable' from 'PROJECT'
ERROR: Unable to find 'libmaxminddb/1.3.2@zhuhaow/stable' in remotes

**Comment by zhuhaow** [comment]
The dependencies for Conan is currently locating in my own repo. I’ll write a instruction about how to use it later.

On 21 Oct 2018, at 17:03, 恨鐵不成金 <notifications@github.com> wrote:

➜ libnekit git:(master) ✗ conan install . --build=missing -s compiler.libcxx=libstdc++
Configuration:
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=10.0
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]

libmaxminddb/1.3.2@zhuhaow/stable: Not found in local cache, looking in remotes...
libmaxminddb/1.3.2@zhuhaow/stable: Trying with 'conan-center'...
ERROR: Failed requirement 'libmaxminddb/1.3.2@zhuhaow/stable' from 'PROJECT'
ERROR: Unable to find 'libmaxminddb/1.3.2@zhuhaow/stable' in remotes

**Comment by honbolau** [comment]
能否将libmaxminddb，boost上传Conan-center

**Comment by zhuhaow** [comment]
Check https://bintray.com/zhuhaow/libnekit

On 22 Oct 2018, at 12:01, 恨鐵不成金 <notifications@github.com> wrote:

能否将libmaxminddb，boost上传Conan-center

**Comment by honbolau** [comment]
ERROR: boost/1.68.0@libnekit/stable: Error in build() method, line 107
	self.run(full_command)
	ConanException: Error 256 while executing /Users/liuhongbao/.conan/data/boost/1.68.0/libnekit/stable/build/1bda08723873b136341953b4c21191e81f5dab82/boost_1_68_0/tools/build/b2 address-model=64 link=static variant=release --without-math --without-wave --without-container --without-contract --without-exception --without-graph --without-iostreams --without-locale --without-program_options --without-random --without-mpi --without-serialization --without-signals --without-coroutine --without-fiber --without-context --without-timer --without-thread --without-chrono --without-date_time --without-atomic --without-filesystem --without-graph_parallel --without-python --without-stacktrace --without-test --without-type_erasure define=_GLIBCXX_USE_CXX11_ABI=0 cxxflags="-fPIC -stdlib=libstdc++" -j4 --abbreviate-paths -d2 --debug-configuration --build-dir="/Users/liuhongbao/.conan/data/boost/1.68.0/libnekit/stable/build/1bda08723873b136341953b4c21191e81f5dab82"

**Comment by honbolau** [comment]
conan install . --build=missing -s compiler.libcxx=libc++, 使用这个命令成功了，但是最后一步的时候又出错了。。。
cmake --build . -- -j2
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [test/subnet_test] Error 1
make[1]: *** [test/CMakeFiles/subnet_test.dir/all] Error 2
make: *** [all] Error 2

但是build目录下的libnekit.a是有了， 说明成功了吗？

**Comment by zhuhaow** [comment]
You can check how it is build on Travis CI 

On 23 Oct 2018, at 08:41, 恨鐵不成金 <notifications@github.com> wrote:

ERROR: boost/1.68.0@libnekit/stable: Error in build() method, line 107
self.run(full_command)
ConanException: Error 256 while executing /Users/liuhongbao/.conan/data/boost/1.68.0/libnekit/stable/build/1bda08723873b136341953b4c21191e81f5dab82/boost_1_68_0/tools/build/b2 address-model=64 link=static variant=release --without-math --without-wave --without-container --without-contract --without-exception --without-graph --without-iostreams --without-locale --without-program_options --without-random --without-mpi --without-serialization --without-signals --without-coroutine --without-fiber --without-context --without-timer --without-thread --without-chrono --without-date_time --without-atomic --without-filesystem --without-graph_parallel --without-python --without-stacktrace --without-test --without-type_erasure define=_GLIBCXX_USE_CXX11_ABI=0 cxxflags="-fPIC -stdlib=libstdc++" -j4 --abbreviate-paths -d2 --debug-configuration --build-dir="/Users/liuhongbao/.conan/data/boost/1.68.0/libnekit/stable/build/1bda08723873b136341953b4c21191e81f5dab82"

**Comment by zhuhaow** [comment]
Add upstream first:

```
conan remote add -f bincrafters https://api.bintray.com/conan/bincrafters/public-conan
conan remote add -f libnekit https://api.bintray.com/conan/zhuhaow/libnekit
```

Then use 

```
conan install (path to conanfile) -s cppstd=14 --build=missing
```

to build.
