### ISSUE TITLE
根据文档我还是不知道如何编译，是否可以帮忙写的更详细一些？

### ISSUE THREAD

**Issue by CocodingLee** [zhuhaow/libnekit#16]
Build the dependencies requires Python 3 and non-antique CMake, install pipenv first then (choose the correct PLATFORM):

pipenv run scripts/build_deps.py PLATFORM
The script will download all dependencies source codes and compile them.

Compile libnekit
It's very likely you don't have to compile libnekit independently, check next subsection.

After all dependencies are successfully built, use CMake to configure and build the project (choose correct platform):

mkdir build && cd build
cmake .. -DCMAKE_TOOLCHAIN_FILE=~/Projects/libnekit/cmake/toolchain/PLATFORM.cmake -DPLATFORM=PLATFORM
cmake --build . -- -j2
libnekit is built but not installed yet. If you want to distribute it, you need to copy all header files from include/, dependencies from deps/PLATFORM/ and libnekit.a to the proper place.

I may add an install target later. But since libnekit requires Boost, the distribution would be too large.

我无法更具上述步骤，编译出libnekit.a, 如果您方便的话，是否可以写的更详细一些？

**Comment by zhuhaow** [comment]
哪里出错了呢？

**Comment by CocodingLee** [comment]
pipenv run scripts/build_deps.py ios

git拉下来的代码中貌似找不到 scripts/build_deps.py 这个文件。

**Comment by CocodingLee** [comment]
> 哪里出错了呢？
非常感谢您的回复。

下面这行命令：
pipenv run scripts/build_deps.py ios
从 github上拉取下来代码，scripts/build_deps.py   这个文件貌似不存在。

**Comment by zhuhaow** [comment]
已经过时了，可以参考 CI 里的方法。

https://github.com/zhuhaow/libnekit/blob/master/.travis.yml

**Comment by zhuhaow** [comment]
这个项目已经很久不更新了，即便你遇到bug我也很可能不会再维护了，因此不建议试用

**Comment by CocodingLee** [comment]
> 这个项目已经很久不更新了，即便你遇到bug我也很可能不会再维护了，因此不建议试用

谢谢您，travis CI我已经开始跑起来了。
目前我是想做一个类似 surge App的小玩具，所以学习一下 libnekit ， 当然最终不会用到商用App里。
